### ISSUE TITLE
gin-middleware  example  is failed

### ISSUE THREAD

**Issue by 66li** [go-lark/examples#3]

**Comment by 66li** [comment]
![image](https://user-images.githubusercontent.com/37136076/154847956-956d8350-5f13-4954-9910-729e8f466e9d.png)

**Comment by crispgm** [comment]
有没有开加密什么的？如果开了的话参数会有所不同

参考这块： https://open.feishu.cn/document/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/event-subscription-configure-/request-url-configuration-case

**Comment by 66li** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/37136076/154886419-82b8175e-9c9f-4499-9948-c1c336c4f7c4.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/37136076/154886437-399909f5-c1ad-4d4c-9362-ed1f9e8f6d49.png">
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/37136076/154886463-8524e299-a0e6-4eb5-929d-bcc6d6abe1fb.png">
你好，我开启了两个参数，并且在exmaple代码里填写了对应的值，还是有同样的报错

**Comment by crispgm** [comment]
URL好像不对，你本身已经r.Group("/lark")了，里面又 POST("lark", ...)
这样相当于 /lark/lark

**Comment by crispgm** [comment]
URL似乎不对 BindURLPrefix 应该是 "/lark/lark"？

**Comment by 66li** [comment]
是的，我直接复制了这个代码，然后地址哪里也加了/lark/lark
https://github.com/go-lark/examples/tree/main/gin-middleware

**Comment by crispgm** [comment]
> 

你试试我上一楼说的，我个人觉得是这个问题，可能是examples写错了

**Comment by 66li** [comment]
好了，多谢
